### ISSUE TITLE
panic: waku flag redefined: filternodes

### ISSUE THREAD

**Issue by D4nte** [status-im/go-waku#33]
On 690841d0420520a55356fd7c307f11b84482c58e

```
▶ uname -a
Linux xps-franck 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64 GNU/Linux
```

```
src/status-im/go-waku  master ✗                                                                                                                                                                                                    14d20h ✖  ⍉
▶ make all 
go build -o build/waku waku.go

src/status-im/go-waku  master ✗                                                                                                                                                                                                   14d20h ✖ ◒  
▶ ./build/waku 
panic: waku flag redefined: filternodes

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00024c600, 0xc000383cc0)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x825
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00024c600, 0x11eefd8, 0xc000470f00, 0xfaccf3, 0xb, 0x0, 0x0, 0xfded5c, 0x58, 0xc00047c078)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringSliceVarP(0xc00024c600, 0xc00047c078, 0xfaccf3, 0xb, 0x0, 0x0, 0x1862b28, 0x0, 0x0, 0xfded5c, ...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string_slice.go:110 +0xe5
github.com/spf13/pflag.(*FlagSet).StringSlice(...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string_slice.go:138
github.com/status-im/go-waku/waku.init.0()
	/home/froyer/src/status-im/go-waku/waku/node.go:254 +0xaab

src/status-im/go-waku  master ✗                                                                                                                                                                                                  14d20h ✖ ◒  ⍉
▶ ./build/waku --help
panic: waku flag redefined: filternodes

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00024e600, 0xc000383cc0)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x825
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00024e600, 0x11eefd8, 0xc000472ef0, 0xfaccf3, 0xb, 0x0, 0x0, 0xfded5c, 0x58, 0xc00046e0d8)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringSliceVarP(0xc00024e600, 0xc00046e0d8, 0xfaccf3, 0xb, 0x0, 0x0, 0x1862b28, 0x0, 0x0, 0xfded5c, ...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string_slice.go:110 +0xe5
github.com/spf13/pflag.(*FlagSet).StringSlice(...)
	/home/froyer/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string_slice.go:138
github.com/status-im/go-waku/waku.init.0()
	/home/froyer/src/status-im/go-waku/waku/node.go:254 +0xaab
```

**Comment by richard-ramos** [comment]
Fixed in https://github.com/status-im/go-waku/commit/73bedde63ca4ee201d040b3e9c5a6bcc35afc515
